name:                geneclocks
version:             0.1.0.0
github:              "dschrempf/geneclocks"
license:             BSD3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2018)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dschrempf/geneclocks#readme>

dependencies:
- base >= 4.7 && < 5
- statistics >= 0.14.0.2
- primitive >= 0.6.3
- mwc-random >= 0.13.6
- text >= 1.2.2
- containers >= 0.5.10.2

library:
  source-dirs: src

executables:
  geneclocks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geneclocks

tests:
  geneclocks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geneclocks
