name:                geneclocks
version:             0.1.0.0
github:              "dschrempf/geneclocks"
license:             BSD3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2018)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dschrempf/geneclocks#readme>

ghc-options:
        - -Wall
        - -Werror

dependencies:
- ansi-wl-pprint
- async >= 2.1.1.1
- base >= 4.7 && < 5
- containers >= 0.5.10.2
- mwc-random >= 0.13.6
- optparse-applicative >= 0.14.0.0
- deepseq >= 1.4.3.0
- parallel >= 3.1.0.1
- primitive >= 0.6.3
- statistics >= 0.14.0.2
- text >= 1.2.2
- vector
- math-functions
- transformers
- monad-logger
- errors

library:
  source-dirs: src

executables:
  simulate-trees:
    main:                SimulateTrees.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    # Remove for production.
    - -eventlog
    dependencies:
    - geneclocks

tests:
  geneclocks-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geneclocks
